### ISSUE TITLE
'behavioral', 'hcp.csv' in dataset.py ?

### ISSUE THREAD

**Issue by xdjwolf** [egyptdj/stagin#1]
I am very interested in your research, and I want to know about the hcp.csv file in your code dataset. Could you please help to provide it?
Because I want to know the specific format and information contained in the CSV table, such as which subjects are involved and their corresponding information, and whether the information is consistent with what I downloaded directly from the HCP.

My Email:  langjw@mail.ustc.edu.cn

**Comment by egyptdj** [comment]
Hi @xdjwolf

I have added an example of the contents included in the `hcp.csv` file to the README.
Please note that IDs of the 'Subject' column from the example does not correspond to the actual HCP dataset, but are just some examples.
