### ISSUE TITLE
Dynamic length missing from rest dataset code

### ISSUE THREAD

**Issue by tuttyfrutyee** [egyptdj/stagin#11]
Hi, again great work.

In your paper, you mention for training, sampling the task data with 150 dynamic_length and sampling resting state data with 600 dynamic_length. Although the code to do this is there for task dataset class, it is not for resting state dataset class. I think this is reflected on the accuracy results I get when I run the code for gender classification, ~83% accuracy compared to %87 mentioned in the paper.

Just wanted to mention it, maybe you could fix it. Thanks...

**Comment by egyptdj** [comment]
Hi @tuttyfrutyee 

The dynamic length is not taken as an argument to the dataset class, but to the 

https://github.com/egyptdj/stagin/blob/1dafb3f945763c4fcf12ffb08f213135e8f8b507/experiment.py#L111
