### ISSUE TITLE
Loading data

### ISSUE THREAD

**Issue by sadaf92** [egyptdj/stagin#12]
Just out of my curiosity, how long does it take for the HCPRest dataset to be loaded as a timeseries dictionary?
(In dataset.py: lines 35-40)
I'm trying on my own dataset and it seems quite slow. But I assume that it is not such a big problem since it will be saved as pth file.

**Comment by egyptdj** [comment]
Hi @sadaf92

It can depend on your CPU performance, but it takes about 56s to parcellate an HCP-Rest image (shaped [91, 109, 91, 1200]) with the Schaefer400 atlas in my local environment.
