### ISSUE TITLE
code cannot run

### ISSUE THREAD

**Issue by shuqincao** [egyptdj/stagin#2]
Can you upload the complete runnable code?

**Comment by egyptdj** [comment]
Hi @shuqincao 

Do you have any error log or error-reproducible script of your run?
The publicly available code itself is not sufficient to run because the HCP dataset should be downloaded and prepared as indicated in the README.md file.

**Comment by shuqincao** [comment]
Thank you for your reply. Can you give me a copy of the data directory

**Comment by egyptdj** [comment]
I am afraid that the data which includes brain image and demographic information of the participants cannot be shared directly.
Please access the Human Connectome Project and accept the data use terms to download the data used in this work.
The [HCP Wiki](https://wiki.humanconnectome.org/display/PublicData/How+to+Access+Data+on+ConnectomeDB) has a great explaination on accessing the HCP data.
