### ISSUE TITLE
About data storage

### ISSUE THREAD

**Issue by wby920920** [egyptdj/stagin#4]
Hello, I am reading your article recently. Appreciate your ideas. I have a question. If the HCP data is prepared according to the instructions in the Readme, the storage space consumption will be large. When you use it, download it to the local and perform subsequent operations.

**Comment by egyptdj** [comment]
Hi @wby920920 

Yes, the raw imaging data may require a few terabytes in your local storage. 
The code extracts ROI-timeseries matrices from the raw images and saves the matrices into a file when you run it for the first time, so you can choose to keep only the ROI-timeseries file afterwards.

**Comment by wby920920** [comment]
When I tried to use the script to extract roi, an error of ‘list index out of range’ appeared as shown in the figure. What is the reason? Will the setting of smoothing_fwhm affect it? 
![image](https://user-images.githubusercontent.com/32837843/140247233-565d5698-8e6e-48ff-a3c4-f2e7878c1d57.png)
The hcp2ts script in the picture is written by completely calling the script you provided。Thanks a lot!

**Comment by egyptdj** [comment]
I think the error is related to the number of items included in the dictionary  `self.timeseries_dict`, which is probably empty.
Items of the `self.timeseries_dict` are added based on the variable defined at the 31st line of the `dataset.py`:

```
img_list = [f for f in os.listdir(os.path.join(sourcedir, 'img', 'REST')) if f.endswith('nii.gz')]
```
so I would like to suggest you to check whether the path `sourcedir/'img'/'REST'` correctly includes fMRI data files that ends with 'nii.gz'

**Comment by wby920920** [comment]
Thank you for your reply! There is another question. In the experiment in the article, how is'smoothing_fwhm' set?

**Comment by wby920920** [comment]
Thank you for your reply! There is another question. In the experiment in the article, how is'smoothing_fwhm' set?

**Comment by egyptdj** [comment]
`smoothing_fwhm`, or the command line option `--fwhm` was implemented for possible use but has not been experimented.
You can leave the default option which will assign `None` to the argument `smoothing_fwhm` if you are not interested in applying spatial smoothing to your fMRI data.

**Comment by wby920920** [comment]
Thanks again for your reply! This helps me a lot.

**Comment by wby920920** [comment]
Thanks again for your reply! This helps me a lot.
